### ISSUE TITLE
[Feqture Request] HTTP reader，processor，writer

### ISSUE THREAD

**Issue by zhenzou** [chararch/gobatch#1]
在我们的实践中，batch 只是负责调度，具体的实现都是在业务服务中实现的，一般的流程是

1. 通过 GET read API 读取一页数据，返回
{
    "data":[],
    "has_next_page":true,
    "next_cursor":"xxx"
}
通过 has_next_page 判断是否还有下一页，用 next_cursor 读下一页数据

2. 将 data 中的每一个 item 作为 body，POST process API
3. 将一页所有 tems 的 process 结果作为 body，POST write API

看能否内置这样一种处理机制。

**Comment by chararch** [comment]
这个流程跟gobatch里的 reader/processor/writer的处理流程是类似的，你所说的内置处理机制是不是想在gobatch里调用HTTP接口？
如果想调用HTTP接口，用gobatch的reader/processor/writer把这3个HTTP接口分别包装一下就可以了，但是HTTP接口跟具体应用有关，其内容格式我们不知道，所以很难固化到框架里。我理解由使用方自己来包装一下比较好，这个应该也比较好实现。不知道有没有解答你的问题？

**Comment by zhenzou** [comment]
我们现在用的 spring batch，所以是在 gobatch 的支持内的，使用方自己做当然没问题。

在我看来，http reader/processor/writer 也是一套通用的 handler，类似于现在内置的 file（csv，json）等，能内置更好而已。
至于格式，可以在 gobatch 内部定义好，或者通过 暴露 decode/encode 的 interface ，都不是问题。

**Comment by zhenzou** [comment]
可能我自己做了，然后看是否通用再提 PR 更合适。

**Comment by chararch** [comment]
嗯，明白你的意思了，欢迎提PR哈
